### ISSUE TITLE
Cannot get test command to work

### ISSUE THREAD

**Issue by vshesh** [herohuyongtao/deeptag-pytorch#1]
hi,

would like to use your framework in a research project where i'll have a webcam tracking 20-50 tags in a scene. 
I tried to clone the repo, install the dependencies (although the requirements.txt file doesn't have exact package names) and when I ran the command I got: 

```
=> python3 test_deeptag.py --config config_image.json

===========> loading model <===========
Cannot load models.
Cannot load codebook: codebook/apriltag_codebook.txt
```

however, i can see that the file `codebook/apriltag_codebook.txt` is there along with other files in the models folder.

Any help to get this working? Would love to try it out! 

thanks

**Comment by vshesh** [comment]
Here is the stacktrace I get: 

```
===========> loading model <===========
Cannot load models.
Traceback (most recent call last):
  File "/deeptag-pytorch/test_deeptag.py", line 41, in <module>
    model_detector, model_decoder, device, tag_type, grid_size_cand_list = load_deeptag_models(tag_family, device)
  File "/deeptag-pytorch/deeptag_model_setting.py", line 78, in load_deeptag_models
    state_dict = torch.load(os.path.join(checkpoint_dir, model_filename))
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Cannot load codebook: codebook/apriltag_codebook.txt
```

Is CUDA or an NVIDIA GPU a requirement to use this library?

**Comment by sskzzm** [comment]
Please use the following command to run the models on CPU (adding "--CPU" to the original command):

 `python test_deeptag.py --config config_image.json --CPU`

**Comment by vshesh** [comment]
Even with the `--CPU` flag I'm seeing the same error from trying to load the pretrained models 

```
=> python3 test_deeptag.py --config config_image.json --CPU
===========> loading model <===========
Cannot load models.
Traceback (most recent call last):
  File "/deeptag-pytorch/test_deeptag.py", line 42, in <module>
    model_detector, model_decoder, device, tag_type, grid_size_cand_list = load_deeptag_models(tag_family, device)
  File "/deeptag-pytorch/deeptag_model_setting.py", line 78, in load_deeptag_models
    state_dict = torch.load(os.path.join(checkpoint_dir, model_filename))
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 787, in _legacy_load
    result = unpickler.load()
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 743, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 175, in default_restore_location
    result = fn(storage, location)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 151, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/usr/local/lib/python3.9/site-packages/torch/serialization.py", line 135, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
```

In the `torch.load` call i don't see a map_location = torch.device('cpu'), so I added it. 
now I see this error which I can't tell is related or not: 

```
===========> loading model <===========
>>>>>>>Stage-1<<<<<<<
8 ROIs
>>>>>>>Stage-2<<<<<<<
>iter #0
>iter #1
Valid ROIs: 0, 1, 2, 3, 4, 6, 7,
------timing (sec.)------
Stage-1 :                    [CNN 2.1845] 2.2217
Stage-2 (1 marker):          [CNN 0.2995] 0.3528
Stage-2 (8 rois, 7 markers): [CNN 2.3963] 2.7936
Traceback (most recent call last):
  File "/deeptag-pytorch/test_deeptag.py", line 89, in <module>
    c = stag_image_processor.visualize(is_pause= not is_video)
  File "/deeptag-pytorch/stag_decode/detection_engine.py", line 227, in visualize
    visualize_rt(image_out_pose, decoded_tag['rvecs'], decoded_tag['tvecs'], self.cameraMatrix, self.distCoeffs, decoded_tag['tag_real_size_in_meter'], tag_id_decimal = tag_id_decimal, tid_text_pos=None, score=None, is_draw_cube =False, rotate_idx=rotate_idx, text_color= None)
  File "/deeptag-pytorch/stag_decode/visualization.py", line 27, in visualize_rt
    image = draw_pose(image,rvecs, tvecs, cameraMatrix, distCoeffs, tag_real_size_in_meter/2, rotate_idx = rotate_idx)
  File "/deeptag-pytorch/util/visualization.py", line 169, in draw_pose
    img = cv2.line(img, corner, tuple(imgpts[0].ravel()), (0,0,255), 5)
cv2.error: OpenCV(4.5.3) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

Exception: python3 exited with 1
[tty 10], line 1: python3 test_deeptag.py --config config_image.json --CPU
```

**Comment by sskzzm** [comment]
Thank you very much for pointing out the above mentioned problems. We have updated the codes to fix these problems.

1) According to the [PyTorch documents](https://pytorch.org/docs/stable/generated/torch.load.html), using "map_location='cpu'" can **avoid GPU RAM surge when loading a model checkpoint**.

2) We have tested the original codes with [opencv-contrib-python (3.4.10.35)](https://pypi.org/project/opencv-contrib-python/3.4.10.35/), and it works fine. It seems that OpenCV(4.5.3) has a strict type requirement when calling **cv2.line()**. The updated codes explicitly convert the points to **Integer**.

**Comment by vshesh** [comment]
Alright I downloaded the code and it works! Thank you.
Now I just need to figure out how to run the detector on frames from a webcam.
